### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by inikishev** [pkmital/time-domain-neural-audio-style-transfer#5]
from this        `     _, height, width, number = map(lambda i: i.value, net.get_shape())`

```
Traceback (most recent call last):
  File "D:\Downloads\Edge\time-domain-neural-audio-style-transfer-master\audio_style_transfer\models\timedomain.py", line 353, in <module>
    run(args['content'], args['style'], args['output'])
  File "D:\Downloads\Edge\time-domain-neural-audio-style-transfer-master\audio_style_transfer\models\timedomain.py", line 305, in run
    result = compute_stylization(
  File "D:\Downloads\Edge\time-domain-neural-audio-style-transfer-master\audio_style_transfer\models\timedomain.py", line 235, in compute_stylization
    _, height, width, number = map(lambda i: i.value, net.get_shape())
  File "D:\Downloads\Edge\time-domain-neural-audio-style-transfer-master\audio_style_transfer\models\timedomain.py", line 235, in <lambda>
    _, height, width, number = map(lambda i: i.value, net.get_shape())
AttributeError: 'int' object has no attribute 'value'
```

**Comment by Ap1075** [comment]
Any solutions on this?
